### USER REGISTRATION
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstname": "anurag",
  "lastname": "reddy",
  "email": "anurag@email.com",
  "password": "author@123",
  "profileImageUrl": "http://example.com/avatar/user.png"
}


### USER AUTHENTICATION (LOGIN)
POST http://localhost:4000/user-api/authenticate
Content-Type: application/json

{
  "email": "anurag@email.com",
  "password": "author@123",
  "role": "USER"
}

### USER AUTHENTICATION (LOGIN SECOND USER)
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "SPR@email.com",
  "password": "user@123"
}

### GET ALL USERS
GET http://localhost:4000/user-api/users

### GET ALL ARTICLES
GET http://localhost:4000/user-api/articles

### GET ARTICLES BY AUTHOR ID
GET http://localhost:4000/user-api/articles/author/69896f3ae6cc1dc714dfc5d0

### COMMENT BY USER
POST http://localhost:4000/user-api/users/comments
Content-Type: application/json

{
  "articleId": "69897c57cd1ce69831ca7bba",
  "userId": "69899bcfceaa6b354900e337",
  "comment": "This is a great article"
}

### AUTHOR REGISTRATION
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstname": "rahul",
  "lastname": "kumar",
  "email": "rahul@author.com",
  "password": "author@123",
  "profileImageUrl": "http://example.com/avatar/author.png"
}
### AUTHOR LOGIN
POST http://localhost:4000/author-api/authenticate
Content-Type: application/json

{
  "email": "rahul@author.com",
  "password": "author@123",
  "role": "AUTHOR"
}

### 2nd author
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstname": "vamshi",
  "lastname": "Reddy",
  "email": "vamshi@author.com",
  "password": "author@123",
  "profileImageUrl": "http://example.com/avatar/author.png"
}
### AUTHOR LOGIN
POST http://localhost:4000/author-api/authenticate
Content-Type: application/json

{
  "email": "vamshi@author.com",
  "password": "author@123",
  "role": "AUTHOR"
}

### CREATE ARTICLE
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "title": "Researching AI djshfjdskfkjsdhfjksdhfjhskjdffnmd",
  "category": "Backend AI",
  "content": "This article explains AI ands backend research."
}


### GET ARTICLES BY AUTHOR
GET http://localhost:4000/author-api/articles/author/69ae8b55b672900e29019f07



### UPDATE ARTICLE
PUT http://localhost:4000/author-api/articles/69ae88fbb672900e29019efb
Content-Type: application/json

{
  "title": "Updating Example",
  "category": "Vehicle",
  "content": "Volvo car is strong"
}
### DELETE ARTICLE
DELETE http://localhost:4000/author-api/articles/69ae88fbb672900e29019efb

### ADMIN LOGIN
POST http://localhost:4000/admin-api/authenticate
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin@123",
  "role": "ADMIN"
}

### ADMIN READ ARTICLES BY AUTHOR
GET http://localhost:4000/admin-api/articles/author/69896f3ae6cc1dc714dfc5d0

### BLOCK USER
PUT http://localhost:4000/admin-api/users/block/69896f29e6cc1dc714dfc5cb

### UNBLOCK USER
PUT http://localhost:4000/admin-api/users/unblock/69896f29e6cc1dc714dfc5cb

### COMMON LOGIN (USER)
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
  "email": "SPR@email.com",
  "password": "user@123"
}

### COMMON LOGIN (AUTHOR)
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
  "email": "rahul@author.com",
  "password": "author@123"
}

### COMMON LOGIN (ADMIN)
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin123"
}

### LOGIN BLOCK CHECK
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
  "email": "anurag@email.com",
  "password": "author@123"
}

### CHANGE PASSWORD
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
  "currentPassword": "author@123",
  "newPassword": "modifypass"
}



### testing of ownership
PUT http://localhost:4000/author-api/articles/69ae88fbb672900e29019efb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlODNjMjg0NjExYTkwMzM5Nzc3ZGEiLCJyb2xlIjoiQVVUSE9SIiwiZW1haWwiOiJyYWh1bEBhdXRob3IuY29tIiwiaWF0IjoxNzczMDQ4NzY1LCJleHAiOjE3NzMwNTIzNjV9.33ldTaQ-nXD4IHeZI6I3DQ_meN1bighP9ZwOVDZ0sh8
Content-Type: application/json

{
  "title": "Updated by Rahul",
  "category": "Backend",
  "content": "Rahul updating his own article"
}
###

PUT http://localhost:4000/author-api/articles/69ae88fbb672900e29019efb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlOGI1NWI2NzI5MDBlMjkwMTlmMDciLCJyb2xlIjoiQVVUSE9SIiwiZW1haWwiOiJ2YW1zaGlAYXV0aG9yLmNvbSIsImlhdCI6MTc3MzA0ODgzMSwiZXhwIjoxNzczMDUyNDMxfQ.F1NcenSiTs8S-8ZOkNGhHpUvHnt87_oJc5tqYgcF8_o
Content-Type: application/json

{
  "title": "Hacking attempt",
  "category": "Backend",
  "content": "Trying to update someone else's article"
}

###
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "title": "AI Research",
  "category": "Backend",
  "content": "Article about AI"
}